# Generated by Django 5.1 on 2026-04-10 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_receipe_user_alter_mealplanner_recipe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userrecipeactivity',
            index=models.Index(fields=['user', 'action'], name='recipes_use_user_id_b7a55e_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecipeactivity',
            index=models.Index(fields=['user', 'recipe', 'action'], name='recipes_use_user_id_c70284_idx'),
        ),
    ]
