# Generated by Django 5.1 on 2024-12-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredients_name',
            field=models.CharField(max_length=255),
        ),
    ]
