# Generated by Django 5.1 on 2025-01-02 07:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_userrecipeactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecipeactivity',
            unique_together={('user', 'recipe', 'action')},
        ),
    ]
