# Generated by Django 5.1 on 2025-01-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_userrecipeactivity_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecipeactivity',
            unique_together=set(),
        ),
    ]
