# Generated by Django 5.1 on 2025-03-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_userrecipeactivity_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipeactivity',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('favorite', 'Favorite')], max_length=10),
        ),
    ]
