# Generated by Django 5.1 on 2025-04-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_userrecipeactivity_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipeactivity',
            name='action',
            field=models.CharField(choices=[('favorite', 'Favorite')], max_length=10),
        ),
    ]
