# Generated by Django 5.1 on 2025-04-05 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
