# Generated by Django 5.1 on 2025-10-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_remove_recipe_image_url_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='image_url',
        ),
    ]
